{{- if .Values.redirectRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.redirectRoute.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.namespace }}
      sectionName: http
  hostnames:
    {{- range .Values.redirectRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
{{- end }}
