{{- if .Values.migrateJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.deployment.name }}-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.migrateJob.backoffLimit }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ .Values.deployment.image }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          command:
            - python
            - manage.py
            - migrate
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
            - secretRef:
                name: {{ .Values.dbSecret.name }}
{{- end }}
