# ArgoCD Application for Filebeat
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
  labels:
    app.kubernetes.io/name: filebeat
    app.kubernetes.io/part-of: reddit-clone
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mohamedmostafa33/nti-final-project-cd.git
    targetRevision: main
    path: helm-charts/filebeat
    helm:
      releaseName: filebeat
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: elk

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
