# ArgoCD Application for Reddit Gateway
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reddit-gateway
  namespace: argocd
  labels:
    app.kubernetes.io/name: reddit-gateway
    app.kubernetes.io/part-of: reddit-clone
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/mohamedmostafa33/nti-final-project-cd.git  # UPDATE THIS
    targetRevision: main
    path: helm-charts/gateway
    helm:
      releaseName: reddit-gateway
      valueFiles:
        - values.yaml
      # Override values if needed
      # values: |
      #   gateway:
      #     name: reddit-gateway
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
